# 1 - Mapper les ports des micro-services dans les ports du service monorepo
# 2 - Recréer une nouvelle instance de postgres pour les micro-services
services:
  monorepo:
    restart: on-failure
    build:
      dockerfile: docker/DEV.Dockerfile
    environment:
      CART_DATABASE_URL: postgres://user:pass@cart-db/cart
      NODE_ENV: development
    ports:
      - '8005:8005'
    volumes:
      - .:/app/

  cart-db:
    image: postgres:17
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: cart
