# 1 - Mapper les ports des micro-services dans les ports du service monorepo
# 2 - Recréer une nouvelle instance de postgres pour les micro-services  
services: 
  monorepo:
    restart: on-failure
    build: 
      dockerfile: docker/DEV.Dockerfile
    depends_on:
      - product-db
    environment:
      PRODUCT_DATABASE_URL: postgres://product-user:product-password@product-db/product
      NODE_ENV: development
      PRODUCT_PORT: 8002
    ports:
      - "8002:8002"
    volumes:
      - .:/app/
    networks:
      - product-network

  product-db:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: product-user
      POSTGRES_PASSWORD: product-password
      POSTGRES_DB: product
    networks:
      - "product-network"

networks:
  product-network:
    driver: bridge

volumes:
  product_data:
