# 1 - Mapper les ports des micro-services dans les ports du service monorepo
# 2 - Recréer une nouvelle instance de postgres pour les micro-services
services:
  monorepo:
    restart: on-failure
    build:
      dockerfile: docker/DEV.Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
    volumes:
      - .:/app/

  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
