# 1 - Mapper les ports des micro-services dans les ports du service monorepo
# 2 - Recréer une nouvelle instance de postgres pour les micro-services
services:
  monorepo:
    restart: on-failure
    build:
      dockerfile: docker/DEV.Dockerfile
    depends_on:
      - category-db
    ports:
      - '8004:8004'
      - '5555:5555'
    environment:
      CATEGORY_DATABASE_URL: ${CATEGORY_DATABASE_URL}
      CATEGORY_PORT: ${CATEGORY_PORT}
      NODE_ENV: development
    volumes:
      - .:/app/

  category-db:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
