openapi: 3.0.0
info:
  title: Category API
  version: 1.0.0
  description: API pour gérer les catégories
servers:
  - url: http://localhost:8004
    description: Serveur de développement

paths:
  /category:
    get:
      summary: Récupérer toutes les catégories
      responses:
        '200':
          description: Liste des catégories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '400':
          description: Erreur lors de la récupération des catégories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Créer une nouvelle catégorie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryRequest'
      responses:
        '201':
          description: Catégorie créée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Erreur de validation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erreur lors de la création de la catégorie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /category/{id}:
    get:
      summary: Récupérer une catégorie par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Catégorie trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Catégorie non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erreur lors de la récupération de la catégorie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Mettre à jour une catégorie par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCategoryRequest'
      responses:
        '200':
          description: Catégorie mise à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Erreur de validation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Catégorie non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erreur lors de la mise à jour de la catégorie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Supprimer une catégorie par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Catégorie supprimée avec succès
        '404':
          description: Catégorie non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erreur lors de la suppression de la catégorie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        slug:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CreateCategoryRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    UpdateCategoryRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    Error:
      type: object
      properties:
        message:
          type: string
