openapi: 3.0.0
info:
  title: Micro-services API
  version: 1.0.0
  description: API documentation for all the entities in the system

tags:
  - name: Categories
    description: Categories management operations

paths:
  /users:
    $ref: './category.swagger.yaml'

components:
  schemas:
    User:
      $ref: './category.swagger.yaml#/components/schemas/Category'
